# Knowledge Extraction Workflow Configuration (v0.2.0)
name: "knowledge-extraction"
version: "0.2.0"
description: "Distills codebase patterns and tricks into a structured library via Survey → Atomize → Librarian."
author: "Knowledge Extraction System"

# Paths (resolve from extraction root; placeholders: {extraction_root}, {project-root})
extraction_root: "{project-root}"
output_plan: "{extraction_root}/_distillation/extraction_plan.json"
output_findings: "{extraction_root}/_distillation/findings"
output_library: "{extraction_root}/_distillation/library"

# Validation
validation: "{installed_path}/checklist.md"

# Optional: batch size for Phase 2 when plan has many targets (e.g. >15)
batch_size: 15

# Exclude paths for Surveyor scan (prefix match; recursive scan skips these)
exclude_paths:
  - "node_modules"
  - ".git"
  - "dist"
  - "build"
  - ".next"
  - "__pycache__"
  - ".venv"
  - "vendor"

# Module path: directory containing this workflow (for validation path resolution)
# When running in-editor from V0.2.0, use "." so validation resolves to ./checklist.md
installed_path: "."
instructions: "" # Optional: path to instructions.md for structured step parsing
